# Generated by Django 4.2.7 on 2023-12-06 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=60)),
                ('sexo', models.CharField(default='Masculino', max_length=15)),
                ('edad', models.IntegerField()),
                ('fecha', models.DateField()),
                ('sueldo', models.FloatField()),
            ],
            options={
                'db_table': 'Empleado',
            },
        ),
    ]
